// <auto-generated />
namespace CompanySchedulces.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Schedules : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Schedules));
        
        string IMigrationMetadata.Id
        {
            get { return "202206031411449_Schedules"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
